services:
  db:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_DB: webapp_db
      POSTGRES_USER: web_user
      POSTGRES_PASSWORD: Abcd1234!
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U web_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_nginx
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "./wait-for-db.sh && nginx -g 'daemon off;'"
    restart: always

volumes:
  pgdata: